import '../styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {NextUIProvider} from "@nextui-org/system";
import I18nProvider from './I18nProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
          <NextUIProvider>
            <I18nProvider>
                {children}
            </I18nProvider>
          </NextUIProvider>
      </body>
    </html>
  )
}
